### ISSUE TITLE
生成的都是空白的pdf

### ISSUE THREAD

**Issue by wanghongbean** [MwumLi/gktimesc2pdf#2]
空白pdf

**Comment by MwumLi** [comment]
这个项目我准备废弃了, 在 README 里面已经写了
@wanghongbean 看这个项目吧  https://github.com/MwumLi/gktimesc2gitbook, 这个项目可以转化为 gitbook, 使用 gitbook 转换静态站点、各种格式电子书更方便。
![image](https://user-images.githubusercontent.com/6889433/87165094-3f6ee200-c2fc-11ea-8ff4-40169a3049c2.png)
